### PR TITLE
remove watermark when dragging out a view

### PR DESCRIPTION
**Pull request by ImranOpenFin**
.wrapper_title {
  display: none !important;
}

### CODE REVIEW

**Comment by vagoel** [comment]
This solution does not work.. 
Please check line no 80 , we do have same css already present.

**Comment by PhilVogt** [comment]
Hi Varun,
Actually its a subtle difference. Imran's one works with;

.wrapper_title {
  **display**: none !important;
}

and not 
.wrapper_title {
    **visibility**: hidden !important;
}

Please give it a go, you will be happy you did.

**Comment by vagoel** [comment]
Hi @PhilVogt  and @ImranOpenFin  ,

I tried multiple times, this solution has no impact and in fact I felt it without even testing it.You are changing the styles for provider window, child windows have no impact of this.

Have you tried the solution on this repo and is it working for you ?

Here is another video after this change is applied -


https://user-images.githubusercontent.com/8045008/110883651-c7d7d380-831e-11eb-8256-d44a2ae82912.mp4

Clearly you will see the watermark when dragging out a view -

Even if you override the child window styles with "stylesheetURL" property in defaultWindowsOptions , there will always be a latency in downloading the css file and parsing it by browser before CSS is applied.Hence watermark is displayed momentarily before the CSS is applied and that's the issue we are trying to solve here.

**Comment by PhilVogt** [comment]
Hey Varun,
Ok, thats very strange. I just checked again with Imran's changes and it is working for me. I will try and understand why it is working for me and not for you. Hopefully we can work it out in the meeting in 15 mins.

Thanks,
Phil.

**Pull request closed without merging**
